### PR TITLE
Rework e-mail message building and support for additional parameters

### PR DESCRIPTION
**Pull request by hctom**
I just reworked the e-mail message building a little to easily allow support of additional parameters. Currently the following are added:

* Message content type
* Reply-To address(es)
* From/sender name

Perhaps there should also be added more parameters to be working out of the box. I am currently e.g. thinking of:

* CC
* BCC
* Read receipt
* Priority

I guess there is still some documentation work needed so users will recognize these new parameters, but I ignored that for now, to get your feedback first.

### CODE REVIEW

**Comment by hctom** [comment]
Damn... I did not check the pull requests before starting to work on this. I just saw there is #3 which does also add the reply-to parameter and also allows setting the message content type. But perhaps my rework of parameter handling might be more future-proof.

**Comment by rhukster** [comment]
Thanks i like your solution... :)

**Comment by hctom** [comment]
Cool thanx. But I will tweak this a little more this evening to have better e-mail/name support, so you might also add names to "to" addresses (currently with my implementation this is only available for sender names). Therefore I will restructure the data to an array with two keys ```mail```and ```name```. Sou you might pass in this array, or just a simple string, that only contains the e-mail address.

And I will also add an admin option to choose the default message content type, so you do not have to explicitly set it in e-mai actions... so be aware of the next pull request ;)

**Comment by flaviocopes** [comment]
Nice! Maybe we can have the content_type setting in the Email plugin options, defaulted to "text/html", what you think? I think it's a good default.

**Comment by flaviocopes** [comment]
Or maybe just leave that as the default for form email sending?

**Comment by hctom** [comment]
Yeah, I also wanted to take text/html as default, because currently all examples utilizing the ```email``` plugin send HTML mails... nut without the appropriate content type set. So this might be a good default.

**Pull request merged**
