### PR TITLE
Config addons

### PR DESCRIPTION
**Pull request by hctom**
Damn... I just messed up my branches, so here is a new pull request which is the successor for #8. I'm sorry for this!

Please read the discussion over there to be up-to-date before continuing here

### CODE REVIEW

**Comment by flaviocopes** [comment]
The blueprint changes (`to.*` and `from.*`) break existing plugin configurations, I got an exception when saving the configuration. So as @rhukster said in https://github.com/getgrav/grav-plugin-email/pull/8, you need to rework that part. I'd leave `to` and `from`, so people don't have to reconfigure that part, and add to_name and from_name. 

Also, can you default to text/html in 

`'content_type' => $this->config->get('plugins.email.content_type', 'text/html'),`

?

Another question, why 

`$message->setContentType($twig->processString($value, $vars));`

and not just 

`$message->setContentType($value);`

?

The rest looks good to me, tested various form options, all fine. Just rework the option names, as we must keep compatibility with the old ones.

**Comment by flaviocopes** [comment]
Additionally, can we think of a way to add an optional plain-text body for html emails? I saw this PR https://github.com/getgrav/grav-plugin-email/pull/9 and the idea is good, just a different (and optional) implementation

E.g.
```
        - email:
            subject: "[Site Contact Form] {{ form.value.name|e }}"
            plain_text_body: "{% include 'forms/data.txt.twig' %}"
            body: "{% include 'forms/data.html.twig' %}"
            to:
              -
                mail: info@example.com
                name: Test user
```

if `plain_text_body` (or choose another property name) is set, provide the html content as the html alternative.

So by default we send html emails, if you want you can only send plain text emails (just set the appropriate content type), and optionally you can send html emails with a plain text version too.

Something like this maybe?

```
$plain_text_available = false;
....

                case 'plain_text_body':
                    $message->setBody($twig->processString($value, $vars), 'text/plain');
                    $plain_text_available = true;
                    break;
                case 'body':
                    if ($plain_text_available) {
                        $message->addPart($twig->processString($value, $vars), 'text/html');
                    } else {
                        $message->setBody($twig->processString($value, $vars));                    }
                    break;
```

**Comment by hctom** [comment]
Yeah, I saw that pull request too, and was also thinking about a similar solution as yours, because the one in the pull request might be a little unflexible if you really want different presentations depending on the content type. So I will give this a try when I reworked the other stuff ;)

**Comment by hugoaf** [comment]
@flaviocopes I'm totally agree with your last solution, templating (forms/data.txt.twig) is the Grav way.

**Comment by hctom** [comment]
So here is my next shot ;) A little summary of what I did:

* Ensured ```text/html```as default value for message content type
* **NOTE:** The content type parameter is still passed through ```$twig->processString()``` to allow dynamic content type assignments (e.g. to let users  choose the desired content type in forms)
* Reworked ```from```and ```to```parameters to be backwards compatible, while introducing additional ```from_name```and ```to_name``` parameters for named e-mail addresses. With this approach it is still possible to add multiple e-mails (as strings or definition arrays - see comments of pull request #8 for details) in e-mail actions
* Added ```charset```parameter with ```utf-8```as default - this parameter is currently not configurable, but may be set in e-mail actions
* Reworked the composition of the e-mail body to allow multiple body parts (which may even use different content types and charsets). When the ```body``` parameter it is added with the configured content type. Provide an array of different body parts in the following form:

````
email:
    subject: '{{ form.value.subject|e }}'
    body:
        -
            content_type: 'text/html'
            body: '{% include ''forms/default/data.html.twig'' %}'
        -
            content_type: 'text/plain'
            body: '{% include ''forms/default/data.txt.twig'' %}'
            charset: 'iso-8859-1'
    reply_to:
        mail: '{{ form.value.email|e }}'
        name: '{{ form.value.name|e }}'
```

I am really looking forward to read your feedback. I hope this covers the topics better now ;) I know this is a lot of stuff, but the plugin really deserves it, hehe

**Comment by flaviocopes** [comment]
Looks good, thanks!

**Comment by flaviocopes** [comment]
@hctom if you want to add some documentation on the new changes in the README.md file, fine! Otherwise I'll add some docs myself. Need to update the Learn site too with the usage along with the Form plugin.

**Comment by hctom** [comment]
@flaviocopes cool thanks for merging! ;) I will provide a pull request for the updated ```README.md``` file asap.

**Pull request merged**
