### PR TITLE
Adding htmlspecialchars_decode() to $body

### PR DESCRIPTION
**Pull request by rikemsen**
Hi there,

I tought it was good to add htmlspecialchars_decode() to $body :)

Best regards

### CODE REVIEW

**Comment by flaviocopes** [comment]
Can you tell which issue does this solve, so I can check? Thanks!

**Comment by rikemsen** [comment]
When receiving an email via the contact form, it displays specials characters like : 

&quot;
&#039;
etc ...

To avoid this, I added htmlspecialchars_decode()

Best regards

**Comment by flaviocopes** [comment]
I'm in doubt if this should be changed here or in the Twig template that generates the email? Need to do a couple tests

**Comment by danbeall73** [comment]
We just made this fix manually in email.php and it works. It would be great if this gets merged

**Comment by flaviocopes** [comment]
Email clients will already interpret emails as HTML. Adding htmlspecialchars_decode() will allow XSS in email clients that do not sanitize JS.

**Pull request closed without merging**
